openapi: 3.0.0
info:
  title: "My API"
  description: "API for managing products"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /products:
    get:
      summary: "Retrieve all products"
      operationId: app.routes.get_all_products
      responses:
        "200":
          description: "A list of products"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: "Create a new product"
      operationId: app.routes.create_product
      requestBody:
        description: "Product to create"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: "Product created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /products/{id}:
    get:
      summary: "Retrieve a specific product by ID"
      operationId: app.routes.get_product_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "A single product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Product not found"

    put:
      summary: "Update an existing product"
      operationId: app.routes.update_product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: "Product to update"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: "Product updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Product not found"

    delete:
      summary: "Delete a product from the database"
      operationId: app.routes.delete_product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Product deleted"
        "404":
          description: "Product not found"

components:
  schemas:
    Product:
      type: object
      properties:
        Item_SKU:
          type: integer
        Item_Name:
          type: string
        Item_Description:
          type: string
        Item_Price:
          type: number
          format: float
        Item_Qty:
          type: integer
        parent_sku:
          type: integer
